services:
  url-preview:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "42069:42069"
    restart: unless-stopped
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
